### ISSUE TITLE
Pom.xml missing for swagger4j 1.0.0 in SmartBear maven repo

### ISSUE THREAD

**Issue by supersmo** [SmartBear/swagger4j#14]
Pom.xml is missing in the smartbear maven repo.
Repository location:
http://smartbearsoftware.com/repository/maven2/com/smartbear/swagger4j/1.0.0/

I am unable to run SoapuiPro tests using ReadyAPI maven plugin 2.4 because of the misssing pom.

**Comment by supersmo** [comment]
Thanks. 
It seems that the checksum for the pom is wrong though.

We're using artifactory to mirror the repo and the pom is rejected because the checksum is wrong.

Sniffed the traffic and captured the following response:

HTTP/1.1 409 Conflict
Date: Tue, 03 Jul 2018 10:15:52 GMT
Content-Type: application/json;charset=ISO-8859-1
Transfer-Encoding: chunked
Connection: keep-alive
Server: Artifactory/6.0.1
X-Artifactory-Id: b1c3080a19e4e559:-3c4bebb5:1645f647b0f:-8000

261
{
  "errors" : [ {
    "status" : 409,
    "message" : "Checksum policy 'GEN_IF_ABSENT' rejected the artifact 'smartbear-cache:com/smartbear/swagger4j/1.0.0/swagger4j-1.0.0.pom'. Checksums info: ChecksumsInfo{checksums={SHA-1=ChecksumInfo{type=SHA-1, original='b77488def2f1729c2e65f0d3909caebb3fb60517', actual='86b218b3d5020f216a103e002f844cfc795a0548'}, MD5=ChecksumInfo{type=MD5, original='b29fa7a7d1154606fb9ca11b2d853647', actual='2d1f4d4797d0d5881755fe265faa8bba'}, SHA-256=ChecksumInfo{type=SHA-256, original='null', actual='1bee6c84e31029fe5940bef0b475c6e8c6e0ff822d65cf5d8f528defa70b7712'}}}"
  } ]
}
0

**Comment by EkaterinaSorokina** [comment]
Please, check once again.

**Comment by supersmo** [comment]
Brilliant!
It works now!
Thanks! :-)
